version: '3'

services:
  web:
    env_file: variables.env
  app:
    user: $USERID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app:Z
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"